spring.application.name=qualityops

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/qualityops
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

## JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.model=nomic-embed-text

# Respostas mais consistentes
spring.ai.ollama.chat.temperature=0.1

# Limite de geração
spring.ai.ollama.chat.num-predict=500

# Limites de tools
spring.ai.tools.limits.max-calls-per-tool-default=3
spring.ai.tools.limits.max-total-tool-calls=10
spring.ai.tools.limits.on-limit-exceeded=THROW

# Ollama configs
spring.ai.ollama.chat.think=false
spring.ai.ollama.chat.keep_alive=30m
spring.ai.ollama.chat.format=json

# Vector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768